#настройка гетвея, это единая точка входа, когда у нас много микросервисов
#гетвей балансирует запролсы т.е перенаправляет их к нужному микросервису
spring:
  application:
    name: GatewayApp
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/